"""add review

Revision ID: 148c3e753866
Revises: dfa4b04fb0f8
Create Date: 2024-11-23 09:08:10.588203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148c3e753866'
down_revision = 'dfa4b04fb0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
